[build.environment]
  YARN_VERSION = "1.22.19"
  NPM_VERSION = "9.1.3"
  NODE_VERSION = "16.13.0"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"
