[build.environment]
  YARN_VERSION = "1.22.19"
  NPM_VERSION = "6.14.16"
  NODE_VERSION = "12.22.12"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"
